### ISSUE TITLE
Documentation for v1.0

### ISSUE THREAD

**Issue by easeev** [chainstack/docs#2]
- [x] Glossary https://github.com/chainstack/core/issues/213
- [x] Protocol selection guide https://github.com/chainstack/core/issues/212
- [x] Consensus selection explainer https://github.com/chainstack/core/issues/245
- [x] Deployment options explainer https://github.com/chainstack/core/issues/247
- [x] Governance selection guide https://github.com/chainstack/core/issues/301
- [x] Getting started guide https://github.com/chainstack/core/issues/310
- [x] Application bootstrapping guide (based on credentials that we provide) https://github.com/chainstack/core/issues/320
- [ ] Network lifecycle guide
- [x] FAQ https://github.com/chainstack/core/issues/360

**Comment by easeev** [comment]
@mcbzz
